### PR TITLE
Board Data | UI Fixes

### LINKED ISSUE #223: Past Board Members data JSON

### PR DESCRIPTION
**Pull request by Safnaj**
Fixes #223
Title Shortened for better SEO
Events Component UI changes

### CODE REVIEW

File: src/app/components/board/board.component.ts [hunk 1]
```diff
@@ -13,7 +12,7 @@ export class BoardComponent implements OnInit {
 
   ngOnInit() {
     this.board = BoardData[2020];
-    console.log(this.board);
+    //console.log(this.board);
     AOS.init();
   }
```
Comment (Safnaj) [inline src/app/components/board/board.component.ts:17]: @Shehanka You need to handle onClick event to fetch the board details year wise.

**Review by Safnaj — COMMENTED** [review]
Left a comment

**Review by Shehanka — APPROVED** [review]

File: src/app/components/board/board.component.ts (hunk 1 above)
Comment (Shehanka) [reply src/app/components/board/board.component.ts:17]: okay! I'll

**Review by Bawanthathilan — APPROVED** [review]
